version: 1.0.{build}

image: Visual Studio 2017
 
install:  
- cmd: curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe  
- cmd: dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log   

branches:
  only:
  - dev
  
build_script:
- ps: .\build.ps1

test: off

artifacts:
- path: artifacts/packages/*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/damiani/
  api_key:
    secure: XOm6HAYrck/gljqdDrLWHopqnOs/FwbstHoi61nIEX6SJNUyccAaLJ4hjsyHoSF8
  skip_symbols: true
  on:
    branch: dev
    
#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /docs.*/
  files:
    - ./*.md