version: '3.4'

services:
  lagencyuser.web:
    image: lagencyuser
    build:
      context: .
      dockerfile: src/LagencyUser.Web/Dockerfile
    ports: 
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: development
      JWT_AUTHORITY: ${JWT_AUTHORITY}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      MONGO_URL: mongodb://user:user@mongo:27017/User
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
      RABBITMQ_QUEUE_NAME: services_queue
    networks:
      - quarksupone
 
networks:
  quarksupone:
    external:
      name: quarksupone