version: '3.4'

services:
  lagencyuser.web:
    image: lagencyuser
    build:
      context: .
      dockerfile: src/LagencyUser.Web/Dockerfile
    ports: 
      - "5011:5011"
    environment:
      - RABBIT_MQ_URL=amqp://mbqxzlgv:RUhVWZbSIFp1raEi96X8zebWpcIJTh5Q@wasp.rmq.cloudamqp.com/mbqxzlgv
      - RABBIT_MQ_QUEUE_NAME=quarksupone
    networks:
      - quarksupone
 
networks:
  quarksupone:
    external:
      name: quarksupone