version: '3.4'

services:
  lagencyuser.web:
    image: lagencyuser
    build:
      context: .
      dockerfile: src/LagencyUser.Web/Dockerfile
    ports: 
      - "5011:5011"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      JWT_AUTHORITY: ${JWT_AUTHORITY}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      MONGO_URL: mongodb://user:user@mongo:27017/User
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE_NAME: ${RABBITMQ_QUEUE_NAME}
    networks:
      - quarksupone
 
networks:
  quarksupone:
    external:
      name: quarksupone