version: '3.4'

services:
  lagencyuser.web:
    image: lagencyuser
    build:
      context: .
      dockerfile: src/LagencyUser.Web/Dockerfile
    ports: 
      - "5011:5011"
    networks:
      - quarksupone
 
networks:
  quarksupone:
    external:
      name: quarksupone