//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagencyUser.Web.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_SharedResource_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_SharedResource_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LagencyUser.Web.Resources.Resources.SharedResource.fr", typeof(Resources_SharedResource_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        internal static string Invalid_login_attempt_ {
            get {
                return ResourceManager.GetString("Invalid login attempt.", resourceCulture);
            }
        }
        
        internal static string Confirm_your_account_ {
            get {
                return ResourceManager.GetString("Confirm your account.", resourceCulture);
            }
        }
        
        internal static string Please_confirm_your_account_by_clicking_this_link___0_ {
            get {
                return ResourceManager.GetString("Please confirm your account by clicking this link: {0}", resourceCulture);
            }
        }
        
        internal static string Error_from_external_provider____0_ {
            get {
                return ResourceManager.GetString("Error from external provider : {0}", resourceCulture);
            }
        }
        
        internal static string Reset_password {
            get {
                return ResourceManager.GetString("Reset password", resourceCulture);
            }
        }
        
        internal static string Please_reset_your_password_by_clicking_here___0_ {
            get {
                return ResourceManager.GetString("Please reset your password by clicking here: {0}", resourceCulture);
            }
        }
        
        internal static string Security_Code {
            get {
                return ResourceManager.GetString("Security Code", resourceCulture);
            }
        }
        
        internal static string Invalid_code_ {
            get {
                return ResourceManager.GetString("Invalid code.", resourceCulture);
            }
        }
        
        internal static string Login_to_your_account {
            get {
                return ResourceManager.GetString("Login to your account", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Forgot_your_password_ {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }
        
        internal static string Create_new_account {
            get {
                return ResourceManager.GetString("Create new account", resourceCulture);
            }
        }
        
        internal static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        internal static string Log_off {
            get {
                return ResourceManager.GetString("Log off", resourceCulture);
            }
        }
        
        internal static string Family_name {
            get {
                return ResourceManager.GetString("Family name", resourceCulture);
            }
        }
        
        internal static string Given_name {
            get {
                return ResourceManager.GetString("Given name", resourceCulture);
            }
        }
        
        internal static string Email_confirmed {
            get {
                return ResourceManager.GetString("Email confirmed", resourceCulture);
            }
        }
        
        internal static string Thank_you_for_confirming_your_email__Please {
            get {
                return ResourceManager.GetString("Thank you for confirming your email. Please", resourceCulture);
            }
        }
        
        internal static string Associate_your__0__account {
            get {
                return ResourceManager.GetString("Associate your {0} account", resourceCulture);
            }
        }
        
        internal static string You_ve_successfully_authenticated_with_0x3cstrong0x3c_0_0x3c_strong0x3c_Please_enter_a_user_name_for_this_site_below_and_click_the_Register_button_to_finishlogging_in_ {
            get {
                return ResourceManager.GetString("You\'ve successfully authenticated with 0x3cstrong0x3c{0}0x3c/strong0x3c.Please en" +
                        "ter a user name for this site below and click the Register button to finishloggi" +
                        "ng in.", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string Login_Failure {
            get {
                return ResourceManager.GetString("Login Failure", resourceCulture);
            }
        }
        
        internal static string Unsuccessful_login_with_service_ {
            get {
                return ResourceManager.GetString("Unsuccessful login with service.", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string Forgot_Password_Confirmation {
            get {
                return ResourceManager.GetString("Forgot Password Confirmation", resourceCulture);
            }
        }
        
        internal static string Please_check_your_email_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("Please check your email to reset your password.", resourceCulture);
            }
        }
        
        internal static string Locked_out_ {
            get {
                return ResourceManager.GetString("Locked out.", resourceCulture);
            }
        }
        
        internal static string This_account_has_been_locked_out__please_try_again_later_ {
            get {
                return ResourceManager.GetString("This account has been locked out, please try again later.", resourceCulture);
            }
        }
        
        internal static string Create_a_new_account {
            get {
                return ResourceManager.GetString("Create a new account", resourceCulture);
            }
        }
        
        internal static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm password", resourceCulture);
            }
        }
        
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        internal static string Reset_password_confirmation {
            get {
                return ResourceManager.GetString("Reset password confirmation", resourceCulture);
            }
        }
        
        internal static string Your_password_has_been_reset__Please {
            get {
                return ResourceManager.GetString("Your password has been reset. Please", resourceCulture);
            }
        }
        
        internal static string Click_here_to_log_in {
            get {
                return ResourceManager.GetString("Click here to log in", resourceCulture);
            }
        }
        
        internal static string Remember_me_ {
            get {
                return ResourceManager.GetString("Remember me?", resourceCulture);
            }
        }
        
        internal static string Personal_informations {
            get {
                return ResourceManager.GetString("Personal informations", resourceCulture);
            }
        }
        
        internal static string Manage_login_services {
            get {
                return ResourceManager.GetString("Manage login services", resourceCulture);
            }
        }
        
        internal static string Managing_general_information__such_as_your_name__e_mail_address__and_phone_number__allows_others_to_find_you_on_various_QuarksupOne_products_and_to_contact_you_ {
            get {
                return ResourceManager.GetString("Managing general information, such as your name, e-mail address, and phone number" +
                        ", allows others to find you on various QuarksupOne products and to contact you.", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Email_address {
            get {
                return ResourceManager.GetString("Email address", resourceCulture);
            }
        }
        
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        internal static string Logins_capability_allow_you_to_login_into_the_application_with_your_socials_account_like_LinkedIn__Google_or_Facebook_ {
            get {
                return ResourceManager.GetString("Logins capability allow you to login into the application with your socials accou" +
                        "nt like LinkedIn, Google or Facebook.", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string Remove_this__0__login_from_your_account {
            get {
                return ResourceManager.GetString("Remove this {0} login from your account", resourceCulture);
            }
        }
        
        internal static string Changing_password_will_be_effective_imediatly__Their_is_no_need_to_disconnect_and_reconnect__No_confirmation_mail_will_be_send_to_you_ {
            get {
                return ResourceManager.GetString("Changing password will be effective imediatly. Their is no need to disconnect and" +
                        " reconnect. No confirmation mail will be send to you.", resourceCulture);
            }
        }
        
        internal static string For_security_purpose_your_password_must_be_at_least_6_characters_long_and_must_contain_at_least_on_digit_ {
            get {
                return ResourceManager.GetString("For security purpose your password must be at least 6 characters long and must co" +
                        "ntain at least on digit.", resourceCulture);
            }
        }
        
        internal static string Old_password {
            get {
                return ResourceManager.GetString("Old password", resourceCulture);
            }
        }
        
        internal static string New_password {
            get {
                return ResourceManager.GetString("New password", resourceCulture);
            }
        }
        
        internal static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
    }
}
