//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagencyUser.Web.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_SharedResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_SharedResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LagencyUser.Web.Resources.Resources.SharedResource", typeof(Resources_SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Invalid_login_attempt_ {
            get {
                return ResourceManager.GetString("Invalid login attempt.", resourceCulture);
            }
        }
        
        internal static string Confirm_your_account_ {
            get {
                return ResourceManager.GetString("Confirm your account.", resourceCulture);
            }
        }
        
        internal static string Please_confirm_your_account_by_clicking_this_link___0_ {
            get {
                return ResourceManager.GetString("Please confirm your account by clicking this link: {0}", resourceCulture);
            }
        }
        
        internal static string Error_from_external_provider____0_ {
            get {
                return ResourceManager.GetString("Error from external provider : {0}", resourceCulture);
            }
        }
        
        internal static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        internal static string Please_reset_your_password_by_clicking_here___0_ {
            get {
                return ResourceManager.GetString("Please reset your password by clicking here: {0}", resourceCulture);
            }
        }
        
        internal static string Security_Code {
            get {
                return ResourceManager.GetString("Security Code", resourceCulture);
            }
        }
        
        internal static string Invalid_code_ {
            get {
                return ResourceManager.GetString("Invalid code.", resourceCulture);
            }
        }
        
        internal static string Login_to_your_account {
            get {
                return ResourceManager.GetString("Login to your account", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Forgot_your_password_ {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }
        
        internal static string Create_new_account {
            get {
                return ResourceManager.GetString("Create new account", resourceCulture);
            }
        }
        
        internal static string Email_confirmed {
            get {
                return ResourceManager.GetString("Email confirmed", resourceCulture);
            }
        }
        
        internal static string Thank_you_for_confirming_your_email__Please {
            get {
                return ResourceManager.GetString("Thank you for confirming your email. Please", resourceCulture);
            }
        }
        
        internal static string Associate_your__0__account {
            get {
                return ResourceManager.GetString("Associate your {0} account", resourceCulture);
            }
        }
        
        internal static string You_ve_successfully_authenticated_with_0x3cstrong0x3c_0_0x3c_strong0x3c_Please_enter_a_user_name_for_this_site_below_and_click_the_Register_button_to_finishlogging_in_ {
            get {
                return ResourceManager.GetString("You\'ve successfully authenticated with 0x3cstrong0x3c{0}0x3c/strong0x3c.Please en" +
                        "ter a user name for this site below and click the Register button to finishloggi" +
                        "ng in.", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string Login_Failure {
            get {
                return ResourceManager.GetString("Login Failure", resourceCulture);
            }
        }
        
        internal static string Unsuccessful_login_with_service_ {
            get {
                return ResourceManager.GetString("Unsuccessful login with service.", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string Forgot_Password_Confirmation {
            get {
                return ResourceManager.GetString("Forgot Password Confirmation", resourceCulture);
            }
        }
        
        internal static string Please_check_your_email_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("Please check your email to reset your password.", resourceCulture);
            }
        }
        
        internal static string Locked_out_ {
            get {
                return ResourceManager.GetString("Locked out.", resourceCulture);
            }
        }
        
        internal static string This_account_has_been_locked_out__please_try_again_later_ {
            get {
                return ResourceManager.GetString("This account has been locked out, please try again later.", resourceCulture);
            }
        }
        
        internal static string Create_a_new_account {
            get {
                return ResourceManager.GetString("Create a new account", resourceCulture);
            }
        }
        
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        internal static string Reset_password_confirmation {
            get {
                return ResourceManager.GetString("Reset password confirmation", resourceCulture);
            }
        }
        
        internal static string Your_password_has_been_reset__Please {
            get {
                return ResourceManager.GetString("Your password has been reset. Please", resourceCulture);
            }
        }
        
        internal static string Click_here_to_log_in {
            get {
                return ResourceManager.GetString("Click here to log in", resourceCulture);
            }
        }
        
        internal static string Remember_me_ {
            get {
                return ResourceManager.GetString("Remember me?", resourceCulture);
            }
        }
    }
}
